#This is dummy data for library management project


books_dicts = [{'author': 'dennis ritchie',
  'book_id': 101,
  'book_in_stock': 50,
  'book_name': 'fundamental of c programming',
  'students_ids': []},
 {'author': 'isaac newton',
  'book_id': 102,
  'book_in_stock': 50,
  'book_name': 'physics',
  'students_ids': []},
 {'author': 'friedrich wohler',
  'book_id': 103,
  'book_in_stock': 30,
  'book_name': 'organic chemistry',
  'students_ids': []},
 {'author': 'richard dawkins',
  'book_id': 104,
  'book_in_stock': 20,
  'book_name': 'the selfish gene',
  'students_ids': []},
 {'author': 'jiawei han',
  'book_id': 105,
  'book_in_stock': 25,
  'book_name': 'data mining',
  'students_ids': []},
 {'author': 'albert einstein',
  'book_id': 106,
  'book_in_stock': 50,
  'book_name': 'physics numerical 2nd edition',
  'students_ids': []},
 {'author': 'wilhelm ostwald',
  'book_id': 107,
  'book_in_stock': 40,
  'book_name': 'physical chemistry',
  'students_ids': []},
 {'author': 'alan kay',
  'book_id': 108,
  'book_in_stock': 30,
  'book_name': 'object oriented programming in java',
  'students_ids': []},
 {'author': 'charles darwin',
  'book_id': 109,
  'book_in_stock': 15,
  'book_name': 'on the origin of species',
  'students_ids': []},
 {'author': 'charles babbage',
  'book_id': 110,
  'book_in_stock': 10,
  'book_name': 'working with dbms',
  'students_ids': []},
 {'author': 'isaac newton',
  'book_id': 111,
  'book_in_stock': 20,
  'book_name': 'calculus 1',
  'students_ids': []},
 {'author': 'isaac newton',
  'book_id': 112,
  'book_in_stock': 20,
  'book_name': 'calculus 2',
  'students_ids': []},
 {'author': 'isaac newton',
  'book_id': 113,
  'book_in_stock': 25,
  'book_name': 'calculus 3',
  'students_ids': []},
 {'author': 'darrell huff',
  'book_id': 114,
  'book_in_stock': 40,
  'book_name': 'how to lie with statistics',
  'students_ids': []},
 {'author': 'trevor hastie',
  'book_id': 115,
  'book_in_stock': 25,
  'book_name': 'the elements of  statistical learning',
  'students_ids': []},
 {'author': 'susanna s. epp',
  'book_id': 116,
  'book_in_stock': 50,
  'book_name': 'discrete mathematics with applications',
  'students_ids': []}]



student_dicts = [{'address': 'zt',
  'class': 'bsc cs',
  'contact': '9897214909',
  'name': 'jackson coffee',
  'semester': 3,
  'student_id': 1},
 {'address': 'gr',
  'class': 'bsc physics',
  'contact': '9862876230',
  'name': 'jhonson tea',
  'semester': 2,
  'student_id': 2},
 {'address': 'tm',
  'class': 'bsc maths',
  'contact': '9894152655',
  'name': 'ellen talker',
  'semester': 7,
  'student_id': 3},
 {'address': 'qn',
  'class': 'bsc chemistry',
  'contact': '9832589631',
  'name': 'rakesh rana',
  'semester': 1,
  'student_id': 4},
 {'address': 'tq',
  'class': 'bsc biology',
  'contact': '9823106248',
  'name': 'ruby red',
  'semester': 2,
  'student_id': 5},
 {'address': 'kq',
  'class': 'msc physics',
  'contact': '9881142670',
  'name': 'scralet charl',
  'semester': 4,
  'student_id': 6},
 {'address': 'vz',
  'class': 'bsc cs',
  'contact': '9876611924',
  'name': 'charl jonshon',
  'semester': 8,
  'student_id': 7},
 {'address': 'tn',
  'class': 'msc maths',
  'contact': '9857368183',
  'name': 'allen walker',
  'semester': 1,
  'student_id': 8},
 {'address': 'ir',
  'class': 'bsc cs',
  'contact': '9880876283',
  'name': 'hari robert',
  'semester': 7,
  'student_id': 9},
 {'address': 'wl',
  'class': 'bsc chemistry',
  'contact': '9845982259',
  'name': 'xin jin',
  'semester': 1,
  'student_id': 10},
 {'address': 'xl',
  'class': 'msc cs',
  'contact': '9881084207',
  'name': 'chau li ',
  'semester': 2,
  'student_id': 11},
 {'address': 'jh',
  'class': 'bsc biology',
  'contact': '9845068598',
  'name': 'kagamaya tobio',
  'semester': 5,
  'student_id': 12},
 {'address': 'fc',
  'class': 'msc physics',
  'contact': '9878325032',
  'name': 'akashi rujaki',
  'semester': 3,
  'student_id': 13},
 {'address': 'iw',
  'class': 'bsc chemistry',
  'contact': '9812159079',
  'name': 'cake pitterson',
  'semester': 5,
  'student_id': 14},
 {'address': 'is',
  'class': 'msc physics',
  'contact': '9854327381',
  'name': 'barni bird',
  'semester': 2,
  'student_id': 15},
 {'address': 'mt',
  'class': 'msc physics',
  'contact': '9814083234',
  'name': 'james kellson',
  'semester': 2,
  'student_id': 16}]




  withdraw_dicts = [{'book_id': 101,
  'return_date': '',
  'student_id': 1,
  'withdraw_date': '2020-05-04'},
 {'book_id': 110,
  'return_date': '',
  'student_id': 1,
  'withdraw_date': '2020-05-04'},
 {'book_id': 102,
  'return_date': '',
  'student_id': 2,
  'withdraw_date': '2020-05-04'},
 {'book_id': 111,
  'return_date': '',
  'student_id': 2,
  'withdraw_date': '2020-05-04'},
 {'book_id': 111,
  'return_date': '',
  'student_id': 3,
  'withdraw_date': '2020-05-04'},
 {'book_id': 114,
  'return_date': '',
  'student_id': 3,
  'withdraw_date': '2020-05-04'},
 {'book_id': 103,
  'return_date': '',
  'student_id': 4,
  'withdraw_date': '2020-05-04'},
 {'book_id': 109,
  'return_date': '',
  'student_id': 5,
  'withdraw_date': '2020-05-04'},
 {'book_id': 103,
  'return_date': '',
  'student_id': 5,
  'withdraw_date': '2020-05-04'},
 {'book_id': 112,
  'return_date': '',
  'student_id': 6,
  'withdraw_date': '2020-05-04'},
 {'book_id': 106,
  'return_date': '',
  'student_id': 6,
  'withdraw_date': '2020-05-04'},
 {'book_id': 105,
  'return_date': '',
  'student_id': 7,
  'withdraw_date': '2020-05-04'},
 {'book_id': 116,
  'return_date': '',
  'student_id': 7,
  'withdraw_date': '2020-05-04'},
 {'book_id': 116,
  'return_date': '',
  'student_id': 8,
  'withdraw_date': '2020-05-04'},
 {'book_id': 115,
  'return_date': '',
  'student_id': 8,
  'withdraw_date': '2020-05-04'},
 {'book_id': 114,
  'return_date': '',
  'student_id': 9,
  'withdraw_date': '2020-05-04'},
 {'book_id': 108,
  'return_date': '',
  'student_id': 9,
  'withdraw_date': '2020-05-04'},
 {'book_id': 107,
  'return_date': '',
  'student_id': 10,
  'withdraw_date': '2020-05-04'},
 {'book_id': 103,
  'return_date': '',
  'student_id': 10,
  'withdraw_date': '2020-05-04'},
 {'book_id': 110,
  'return_date': '',
  'student_id': 11,
  'withdraw_date': '2020-05-04'},
 {'book_id': 109,
  'return_date': '',
  'student_id': 12,
  'withdraw_date': '2020-05-04'},
 {'book_id': 107,
  'return_date': '',
  'student_id': 12,
  'withdraw_date': '2020-05-04'},
 {'book_id': 102,
  'return_date': '',
  'student_id': 13,
  'withdraw_date': '2020-05-04'},
 {'book_id': 107,
  'return_date': '',
  'student_id': 14,
  'withdraw_date': '2020-05-04'},
 {'book_id': 102,
  'return_date': '',
  'student_id': 15,
  'withdraw_date': '2020-05-04'},
 {'book_id': 103,
  'return_date': '',
  'student_id': 15,
  'withdraw_date': '2020-05-04'}]


  return_dicts = [{'book_id': 101, 'student_id': 1},
 {'book_id': 110, 'student_id': 1},
 {'book_id': 103, 'student_id': 5},
 {'book_id': 116, 'student_id': 8},
 {'book_id': 111, 'student_id': 3},
 {'book_id': 114, 'student_id': 9},
 {'book_id': 107, 'student_id': 12}]


